openapi: 3.0.0
info:
  title: Data Platform Management API
  description: |-
    This API enables the management of data processing workloads within a data platform. It provides endpoints for creating, updating, deleting, and retrieving workloads, as well as monitoring their status and performance.
      
    Some useful links:
    - [API prototype Repository](https://github.com/bastoska/plataforma-dados-api)
  version: 1.0.0
servers:
  - url: https://api.yourdomain.com/api/v1
    description: Production server
  - url: http://localhost:8080/api/v1
    description: Development server
tags:
  - name: workload
    description: Workload Endpoints
  # - name: workloads/batch
  #   description: Everything about your Workloads
paths:
  /workloads:
    get:
      tags:
        - workload
      summary: Retrieve all workflows
      description: Fetches a list of all data processing workflows.
      parameters:
        - name: param1
          in: query
          description: Description of param1
          required: true
          schema:
            type: string
            example: example1
      responses:
        '200':
          description: A list of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkloadBase'
        '400':
          description: Bad request
  /workloads{id}:
    delete:
      tags:
        - workload
      summary: Delete a specific workload
      description: Deletes a specific workload by its ID. Deleting a workload means that the related cloud resources will be deleted.
      parameters:
        - name: id
          in: path
          description: Workload ID
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Batch workload deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
          
  /workloads/listByLabelKey:
    get:
      tags:
        - workload
      summary: List Workloads by google cloud label keys
      description: Multiple keys can be provided with comma separated strings. Use environment, tag2, deparment for testing.
      operationId: listByLabelKey
      parameters:
        - name: key
          in: query
          description: Keys to filter by
          required: false
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Workload list by keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkloadBase'
        '400':
          description: Invalid tag value
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
  /workloads/listByStatus:
    get:
      tags:
        - workload
      summary: List Workloads by status
      description: Multiple keys can be provided with comma separated strings. Use environment, tag2, deparment for testing.
      operationId: listByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: false
          explode: true
          schema:
            type: string
            default: created
            enum:
              - created
              - pending
              - active
              - canceled
      responses:
        '200':
          description: Workload list by keys
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WorkloadBase'
        '400':
          description: Invalid tag value
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
  /workloads/batch/{id}:
    get:
      tags:
        - workload
      summary: Retrieve a specific batch workload
      description: Fetches details of a specific batch workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the batch workload
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Batch workload details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchWorkload'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
    
    put:
      tags:
        - workload
      summary: Update a specific batch workload
      description: Updates details of a specific batch workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the batch workload
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated batch workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBatchWorkload'
      responses:
        '200':
          description: Batch workload updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchWorkload'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error

    # delete:
    #   tags:
    #     - workload
    #   summary: Delete a specific batch workload
    #   description: Deletes a specific batch workload by its ID.
    #   parameters:
    #     - name: id
    #       in: path
    #       description: ID of the batch workload
    #       required: true
    #       schema:
    #         type: integer
    #   responses:
    #     '204':
    #       description: Batch workload deleted successfully
    #     '401':
    #       description: Unauthorized
    #     '404':
    #       description: Not Found
    #     '408':
    #       description: Request Timeout
    #     '500':
    #       description: Internal Server Error


  /workloads/stream/{id}:
    get:
      tags:
        - workload
      summary: Retrieve a specific stream workload
      description: Fetches details of a specific stream workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the stream workload
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Stream workload details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamingWorkload'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
    
    put:
      tags:
        - workload
      summary: Update a specific stream workload
      description: Updates details of a specific stream workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the stream workload
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated stream workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBatchWorkload'
      responses:
        '200':
          description: Stream workload updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchWorkload'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error

    # delete:
    #   tags:
    #     - workload
    #   summary: Delete a specific stream workload
    #   description: Deletes a specific stream workload by its ID.
    #   parameters:
    #     - name: id
    #       in: path
    #       description: ID of the stream workload
    #       required: true
    #       schema:
    #         type: integer
    #   responses:
    #     '204':
    #       description: Stream workload deleted successfully
    #     '401':
    #       description: Unauthorized
    #     '404':
    #       description: Not Found
    #     '408':
    #       description: Request Timeout
    #     '500':
    #       description: Internal Server Error


  /workloads/async/{id}:
    get:
      tags:
        - workload
      summary: Retrieve a specific async workload
      description: Fetches details of a specific async workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the async workload
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Async workload details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncWorkload'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
    
    put:
      tags:
        - workload
      summary: Update a specific async workload
      description: Updates details of a specific async workload by its ID.
      parameters:
        - name: id
          in: path
          description: ID of the async workload
          required: true
          schema:
            type: integer
      requestBody:
        description: Updated async workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBatchWorkload'
      responses:
        '200':
          description: Async workload updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchWorkload'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error

    # delete:
    #   tags:
    #     - workload
    #   summary: Delete a specific async workload
    #   description: Deletes a specific async workload by its ID.
    #   parameters:
    #     - name: id
    #       in: path
    #       description: ID of the async workload
    #       required: true
    #       schema:
    #         type: integer
    #   responses:
    #     '204':
    #       description: Async workload deleted successfully
    #     '401':
    #       description: Unauthorized
    #     '404':
    #       description: Not Found
    #     '408':
    #       description: Request Timeout
    #     '500':
    #       description: Internal Server Error


  /workloads/batch:
    post:
      tags:
        - workload
      summary: Create a new batch workload
      description: Creates a new batch data processing workload.
      requestBody:
        description: Batch workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBatchWorkload'
      responses:
        '201':
          description: Batch workload created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error


  /workloads/stream:
    post:
      tags:
        - workload
      summary: Create a new streaming workload
      description: Creates a new streaming data processing workload.
      requestBody:
        description: Streaming workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewStreamingWorkload'
      responses:
        '201':
          description: Streaming workload created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error


  /workloads/async:
    post:
      tags:
        - workload
      summary: Create a new async workload
      description: Creates a new async data processing workload.
      requestBody:
        description: Async workload details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewAsyncWorkload'
      responses:
        '201':
          description: Async workload created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error

          
components:
  schemas:
    WorkloadBase:
      type: object
      properties:
        id:
          type: integer
          example: 1
        workload_type:
          type: string
          enum:
            - batch
            - streaming
            - async
          example: batch
        name:
          type: string
          example: 'Data Processing Workload'
        status:
          type: string
          example: 'active'
          enum:
            - placed
            - approved
            - delivered
        created_at:
          type: string
          format: date-time
          example: '2024-07-20T12:00:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2024-07-23T12:00:00Z'
        data_source_type:
          type: string
          example: database
          enum:
            - file
            - database
            - message
        data_source_location:
          type: string
          example: aws
          enum:
            - on-premise
            - gcp
            - aws
            - azure
            - oci
        data_destination_type:
          type: string
          example: gcs
          enum:
            - bigquery
            - gcs
            - bigtable
            - topic
        processing_type:
          type: string
          example: 'cpu'
          enum:
            - cpu
            - gpu
        gcp_labels:
          type: object
          additionalProperties:
            type: string
          example:
            env: development  
            department: marketing
    NewWorkload:
      type: object
      properties:
        workload_type:
          type: string
          enum:
            - batch
            - streaming
            - async
        name:
          type: string
          example: 'Data Processing Workload'
        data_source_type:
          type: string
          enum:
            - file
            - database
            - message
        data_source_location:
          type: string
          enum:
            - on-premise
            - gcp
            - aws
            - azure
            - oci
        data_destination_type:
          type: string
          enum:
            - bigquery
            - gcs
            - bigtable
            - topic
        processing_type:
          type: string
          example: 'active'
          enum:
            - cpu
            - gpu
    BatchWorkload:
      allOf:
        - $ref: '#/components/schemas/WorkloadBase'
        - type: object
          properties:
            specification:
              type: object
              properties:
                update_frequency:
                  type: string
                  enum:
                    - daily
                    - weekly
                    - monthly
                    - quartely
                retries:
                  type: integer
          example:
            id: 1
            workload_type: "batch"
            name: 'customer-analytics'
            status: 'pending'
            created_at: '2024-07-20T12:00:00Z'
            updated_at: '2024-07-22T12:00:00Z'
            data_source_type: 'database'
            data_source_location: "aws"
            data_destination_type: "bigquery"
            gcp_labels:
              env: development  
              department: marketing
            processing_type: cpu
            specification:
              update_frequency: "daily"
              reties: 5
              data_destination_dataset: "dataset_name"
              data_destination_table: "table_name"
    NewBatchWorkload:
      allOf:
        - $ref: '#/components/schemas/NewWorkload'
        - type: object
          properties:
            specification:
              type: object
              properties:
                update_frequency:
                  type: string
                  enum:
                    - daily
                    - weekly
                    - monthly
                    - quartely
                retries:
                  type: integer
          example:
            workload_type: "batch"
            name: 'customer-analytics'
            data_source_type: 'database'
            data_source_location: "aws"
            data_destination_type: "bigquery"
            processing_type: cpu
            specification:
              update_frequency: "daily"
              reties: 5
              data_destination_dataset: "dataset_name"
              data_destination_table: "table_name"
    StreamingWorkload:
      allOf:
        - $ref: '#/components/schemas/WorkloadBase'
        - type: object
          properties:
            specification:
              type: object
              properties:
                aggregation_window_seconds:
                  type: number
                  nullable: true
                event_by_event_processing:
                  type: boolean
                  nullable: true
                delivery_type:
                  type: string
                  enum:
                    - at_least
                    - at_most
                    - exactly
          example:
            id: 2
            workload_type: "streaming"
            name: 'network-analytics'
            status: 'pending'
            created_at: '2024-07-21T12:00:00Z'
            updated_at: '2024-07-23T12:00:00Z'
            data_source_type: 'message'
            data_source_location: "gcp"
            data_destination_type: "bigquery"
            processing_type: cpu
            gcp_labels:
              env: development  
              department: data-platform
            specification:
              oneOf:
                - aggregation_window_seconds: 5
                - event_by_event_processing: true
              delivery_type: at_leat
    NewStreamingWorkload:
      allOf:
        - $ref: '#/components/schemas/WorkloadBase'
        - type: object
          properties:
            specification:
              type: object
              properties:
                aggregation_window_seconds:
                  type: number
                  nullable: true
                event_by_event_processing:
                  type: boolean
                  nullable: true
                delivery_type:
                  type: string
                  enum:
                    - at_least
                    - at_most
                    - exactly
          example:
            workload_type: "streaming"
            name: 'network-analytics'
            data_source_type: 'message'
            data_source_location: "gcp"
            data_destination_type: "bigquery"
            processing_type: cpu
            specification:
              oneOf:
                - aggregation_window_seconds: 5
                - event_by_event_processing: true
              delivery_type: at_leat       
    AsyncWorkload:
      allOf:
        - $ref: '#/components/schemas/WorkloadBase'
        - type: object
          properties:
            specification:
              type: object
              properties:
                trigger_event:
                  type: string
                  enum:
                    - file_upload
                    - topic_message
                    - http_request
                  example: 'file_upload'
          example:
            id: 3
            workload_type: async
            name: 'file-processing'
            status: 'active'
            created_at: '2024-07-20T12:00:00Z'
            updated_at: '2024-07-23T12:00:00Z'
            data_source: 'gs://uploaded-files-bucket'
            data_destination: 'gs://processed-files-bucket'
            processing_type: cpu
            gcp_labels:
              env: development  
              department: marketing
            specification:
              trigger_event: 'file_upload'
    NewAsyncWorkload:
      allOf:
        - $ref: '#/components/schemas/WorkloadBase'
        - type: object
          properties:
            specification:
              type: object
              properties:
                trigger_event:
                  type: string
                  enum:
                    - file_upload
                    - topic_message
                    - http_request
                  example: 'file_upload'
          example:
            workload_type: async
            name: 'file-processing'
            data_source: 'gs://uploaded-files-bucket'
            data_destination: 'gs://processed-files-bucket'
            processing_type: cpu
            specification:
              trigger_event: 'file_upload'